CREATE USER IF NOT EXISTS 'app-polimi'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*F3F5F3972FFA4C71963629A048D91169DF269AE6' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;

GRANT USAGE ON *.* TO `app-polimi`@`%`;
GRANT SELECT, INSERT, UPDATE, DELETE ON `tiw-project`.* TO `app-polimi`@`%`;
